title = "WRCCDC"
baseURL = "https://wrccdc.org/"
languageCode = "en-us"
theme = "ananke"
# themesDir = "../.."

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "images/favicon/favicon.ico"
  description = "Western Regional Collegiate Cyber Defense Competition"
  facebook = "https://facebook.com/wrccdc"
  twitter = "https://twitter.com/wrccdc"
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  body_classes = "avenir bg-near-white"
  featured_image = "/images/cover.jpg"
  recent_posts_number = 2
  ShowDatesOnPosts = false
  mainSections = ["Seasons"] #index page "recent" section. Also, activates twitter form.
  custom_css = ["css/custom.css"]

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      nofollowLinks = false
      fractions = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = true
      xHTML = true
    [markup.highlight]
      codeFences = true
      guessSyntax = false
      lineNos = true
      lineNumbersInTable = false
      noClasses = true
      style = "monokai"
      tabWidth = 4
    [markup.tableOfContents]
      endLevel = 3
      ordered = false
      startLevel = 2

[[menu.main]]
name = "Store"
weight = 0
identifier = "Store"
url = "https://the-pier-at-coastline-college.myshopify.com/collections/WRCCDC-collection"