title = "WRCCDC"
baseURL = "https://wrccdc.org/"
languageCode = "en-us"
theme = "ananke"
# themesDir = "../.."

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "images/favicon/favicon.ico"
  description = "Western Regional Collegiate Cyber Defense Competition"
  facebook = "https://facebook.com/wrccdc"
  twitter = "https://twitter.com/wrccdc"
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  body_classes = "avenir bg-near-white"
  featured_image = "/images/cover.jpg"
  recent_posts_number = 2
  ShowDatesOnPosts = false
  mainSections = ["Seasons"] #index page "recent" section. Also, activates twitter form.
  custom_css = ["css/custom.css"]
